config/routes.rb
Rails.application.routes.draw do
  resources :chats

  root 'chats#index'

end

app/models/chat.rb
class Chat < ActiveRecord::Base
    validates :name, presence: true, length: { in: 2..8 }
    validates :message, presence: true, length: { in: 2..140 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :set_chat, only: [:show, :edit, :update, :destroy]

  # GET /chats
  # GET /chats.json
  def index
    @chat = Chat.new
    @chats = Chat.all.order(created_at: :desc)
  end

  # GET /chats/1
  # GET /chats/1.json
  def show
  end

  # GET /chats/new
  def new
    @chats = Chat.all
  end

  # GET /chats/1/edit
  # def edit
  # end

  # POST /chats
  # POST /chats.json
  def create
    @chat = Chat.new(chat_params)

    respond_to do |format|
      if @chat.save
        format.html { redirect_to root_path, notice: 'Message was successfully posted.' }
        format.json { render :show, status: :created, location: @chat }
      else
        format.html { render :new }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chats/1
  # PATCH/PUT /chats/1.json
  # def update
  #   respond_to do |format|
  #     if @chat.update(chat_params)
  #       format.html { redirect_to @chat, notice: 'Chat was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @chat }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @chat.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /chats/1
  # DELETE /chats/1.json
  def destroy
    @chat.destroy
    respond_to do |format|
      format.html { redirect_to chats_url, notice: 'Chat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chat
      @chat = Chat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chat_params
      params.require(:chat).permit(:name, :message)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/views/chats/_form.html.erb
<%= form_for @chat, validate: true do |f| %>
  <% if @chat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chat.errors.count, "error") %> prohibited this chat from being saved:</h2>

      <ul>
      <% @chat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_area :message %>
  </div>
  <div class="actions">
    <%= f.submit 'Send Messsage' , :class => 'waves-effect waves-light btn' %>
  </div>
<% end %>

app/views/chats/index.html.erb
<div class="row">
  <h1 class="center">MNR Public Chat</h1>
  <div class="col s6">
<% @chats.each do |chat| %>
<p>
<p><h6><%= chat.name %> said:</h6> <%= chat.message %> at <%= chat.created_at %></p>  
</p>
<hr />
<% end %>    
  </div>
  
  <div class="col s6">

<%= render 'form' %>
<p id="notice"><%= notice %></p>    
  </div>
</div>





<br>

app/views/chats/new.html.erb
<% @chats.each do |chat| %>
<p>
  <hr />
<p><h6><%= chat.name %> said:</h6> <%= chat.message %></p>  
</p>
<hr />
<% end %>
<br>

app/views/chats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @chat.name %>
</p>

<p>
  <strong>Message:</strong>
  <%= @chat.message %>
</p>

<%= link_to 'Edit', edit_chat_path(@chat) %> |
<%= link_to 'Back', chats_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MNR PUBLIC CHAT</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
<%= yield %>  
</div>


</body>
</html>